### ISSUE TITLE
search string: string has to start at beginning (not a sub-string at the end of the original search string)

### ISSUE THREAD

**Issue by zWhdmB5T** [2factorauth/2fa.directory#68]
### bug noticed

when searching "2factorauth/twofactorauth" for "Thalia" (German book store), I have to enter "Thalia" or at least a sub-string starting at the beginning of the original string, e.g. "Thali" or even "Tha".
—
But a sub-string starting later (not at the first position of the original string) does not work, e.g. "alia" (missing "Th") gives "Allianz" and "AliExpress", but not "Thalia".

**Comment by Carlgo11** [comment]
Hello @zWhdmB5T,
What you're describing is the intended behavior.

We use Algolia for the search field, and their recommended behavior is to accept one wrong letter on a 4-character search query and two wrong letters on an 8-character search query.
![Algolia](https://github.com/user-attachments/assets/ef015de5-ef67-4bba-8c24-82738534ef7e)

**Comment by zWhdmB5T** [comment]
@Carlgo11 thank you!
