### ISSUE TITLE
search: difference between site to search and search parameter

### ISSUE THREAD

**Issue by zWhdmB5T** [2factorauth/2fa.directory#69]
### bug noticed
I tried to search for "Yubico". I get many(!) sites using the Yubico OTP method — but I just want the "Yubico" site itself. The search entry should be for the sites/companies/domains — but not for the parameters. Maybe introduce a specific parameter box for things like "Yubico" or "TOTP".

**Comment by Carlgo11** [comment]
Yubico is a 2FA provider and, thus, not a site that we list. If the website existed in our directory, the search field would function as you suggested.
Furthermore, search parameters are available. `2fa:totp` for example.

**Comment by zWhdmB5T** [comment]
@Carlgo11 thank you!
