### ISSUE TITLE
search: get several (i.e. 3) results the same on specific search strings, like "ionos"

### ISSUE THREAD

**Issue by zWhdmB5T** [2factorauth/2fa.directory#70]
Dear all,

when looking for some specific search strings, I get several (i.e. 3) results the same.

Like "ionos". I get 3 results for that. They all look the same, I cannot see a difference.

Another example is "amazon". There are several (i.e. 6) results in total of which 3 seem to be the same, again.

Is there an actual difference. Or what is that?

Thank you!

**Comment by Carlgo11** [comment]
Ionos and Amazon Web Services (AWS) offer domain registration, cloud computing resources, and web hosting. Hence the existence in three different categories.

The search field shows users all the occurrences of matching websites. If it didn't, people would be confused about why their hosting provider only shows up under the domain category when searching for it.
